name: 'Deploy a config file to Portainer'
description: 'Github Action to deploy a config to a Portainer instance'
author: 'Ahmed Anwar <AA-Hamza>'
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  portainer-host:
    required: true
    description: 'Portainer host, eg. https://myportainer.instance.com'
  username:
    required: true
    description: 'Username for the Portainer login. NOTE: Do not use admin account! Create a new CI specific login'
  password:
    required: true
    description: 'Password for the Portainer login'
  endpoint-id:
    required: false
    description: 'ID of the Portainer node to deploy to'
  config-name:
    required: true
    description: 'Name for the config'
  config-definition:
    required: false
    description: 'The path to the config file'
  reject-unauthorized:
    required: false
    description: 'Reject unauthorized SSL certificates'
    default: true

runs:
  using: 'node20'
  main: 'dist/index.js'
